[project]
name = "trucbidule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-vite>=3.1.0",
    "django>=5.1.7",
    "pytest>=8.3.5",
    "django-environ>=0.12.0",
    "django-browser-reload>=1.18.0",
]
